### ISSUE TITLE
Error response is 404 where 400 was expected

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/goci-rest#1]
When I run:

```bash
curl 'https://www.ebi.ac.uk/gwas/rest/api/studies/123' -i -H 'Accept: application/json'
```

According to the REST API documentation ([Errors](https://www.ebi.ac.uk/gwas/rest/docs/api#_example_response)), I expected an error response 400 with a JSON object describing the problem but instead I get this:

```
HTTP/2 404 
server: Apache-Coyote/1.1
cache-control: no-cache, no-store, max-age=0, must-revalidate
strict-transport-security: max-age=0
date: Sun, 07 Oct 2018 10:17:38 GMT
x-application-context: application
expires: 0
x-xss-protection: 1; mode=block
pragma: no-cache
x-content-type-options: nosniff
x-frame-options: DENY
```

**Comment by ramiromagno** [comment]
Hi @tburdett - I see... you might have changed this recently, but the docs still has a typo in the Errors section, see [Errors](https://www.ebi.ac.uk/gwas/rest/docs/api#overview-errors):

For example, a request that attempts to apply a non-existent tag to a resource **will produce a 400 Bad Request response**:

```
HTTP/1.1 404 Not found
Content-Type: application/json;charset=UTF-8
Content-Length: 168

{"timestamp":1526981476169,"status":404,"error":"Not Found","message":"The tag 'https://www.ebi.ac.uk/gwas/rest/api/studies/123' the resource did not exist","path":"/notes"}
```

**Comment by cmalangone** [comment]
Hi Ramiro,
I opened a jira ticket and I noticed that I forgot the sentence:
https://www.ebi.ac.uk/panda/jira/browse/GOCI-2438

**Comment by ramiromagno** [comment]
@cmalangone: no problem.

Thanks for fixing this!
