### ISSUE TITLE
Example URLs in the docs need update

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/goci-rest#2]
All example URLs in [https://www.ebi.ac.uk/gwas/rest/docs/api](https://www.ebi.ac.uk/gwas/rest/docs/api) still include the `/labs/` in their path.

Example: 

```bash
curl 'https://www.ebi.ac.uk/gwas/labs/rest/api/studies?page=1&size=1' -i
```

should read instead:

```bash
curl 'https://www.ebi.ac.uk/gwas/rest/api/studies?page=1&size=1' -i
```

**Comment by tburdett** [comment]
This has now been updated - thanks for reporting this!
