### ISSUE TITLE
/singleNucleotidePolymorphisms/rs11974409/studies elicits a 500 response

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/goci-rest#38]
A user of gwasrapidd found that this SNP triggers a 500 response:

<https://www.ebi.ac.uk/gwas/rest/api/singleNucleotidePolymorphisms/rs11974409/studies>

![snap](https://user-images.githubusercontent.com/19862384/187675964-f652e106-06f9-4c0e-a062-174546f6b300.png)

**Comment by ljwh2** [comment]
@sprintell please confirm this is now resolved?
