### ISSUE TITLE
The field publication date is different between the web UI and the REST API

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci-rest#9]
Publication date differs between the web UI and the REST API outputs.
Example: Recent COVID-19 publications (pubmed id: 32558485 and 32404885), output below is obtained from using R client to the REST API
The two dates here shown: 2020-06-16 and 2020-05-12, are actually one day before the correct date.
The web UI returns it correctly but Rest API's date is 1 day backwards

**Comment by jdhayhurst** [comment]
I checked here, but it the date is still 1 day back:
/gwas/rest/api/studies/search/findByPublicationIdPubmedId?pubmedId=32558485

**Comment by ljwh2** [comment]
@jdhayhurst to test please

**Comment by jdhayhurst** [comment]
Tested on snoopy - works
